### ISSUE TITLE
Climate temperature change issues

### ISSUE THREAD

**Issue by DirkMu** [XKNX/xknx#1033]
**Description of problem:**
I don't know if this is specific to my device but I thought it might be worth reporting it here. 

When I have activated a preset mode other than Comfort, such a standby/away or night and I  change the target temperature from home assistant by e.g. 0,5 degrees the value changes by 1,5 degress. I assume this is due to the setting 'target value reduction' set in the knx application (see image 1) which is relative to the value of the value set for comfort. 

When the target temperature is changed from the thermostat directly (preset mode is active) everythings works correctly. 

I don't know if this is specific to the Hager WYT62x or somethings that is valid for other manufactures, too. Further if this can be handled by xknx. As you can see in image 3 19,5 degrees was received from tunnel 2. The thermostat resonded with 18,5 degrees. Any idea how the device itself handles this? 

When preset mode comfort is active everything works fine. 

- [ ] using xknx standalone
- [X] using Home-Assistant knx integration

**Version information:**
- xknx / Home-Assistant release with the issue: 1.0.2
- last working xknx / Home-Assistant release (if known):

**KNX installation:**
Hager WYT62x thermostat

![image](https://user-images.githubusercontent.com/53949754/191820663-8bb1b5dd-8e80-4ffc-afa0-0764d6330054.png)
![image](https://user-images.githubusercontent.com/53949754/191820891-038d001f-2264-4cbf-9be0-c07a32f44c4b.png)
![image](https://user-images.githubusercontent.com/53949754/191825446-efadb919-9083-45fa-9f7e-744221707f53.png)

**Problem-relevant `configuration.yaml` entries (fill out even if it seems unimportant):**
```
- name: bad
  temperature_address: '4/2/65'
  target_temperature_address: '4/2/63'
  target_temperature_state_address: '4/2/64'
  operation_mode_state_address: '4/2/62'
  operation_mode_address: '4/2/61'
  temperature_step: 0.5
  command_value_state_address: '4/2/66'
  active_state_address: '4/2/68'
  min_temp: 18
  max_temp: 25
```

**Diagnostic data of the config entry (only when Home Assistant is used)**

**Traceback (if applicable):**
Set a preset mode other than comfort (or whatever the default is) and change the target temperature

**Comment by farmio** [comment]
Hi 👋! 
Sorry for the late answer. 

Unfortunately there doesn't seem to be consensus about how target temperatures are set in Knx. Every manufacturer seems to implement their own ideas for that 😭

Is there maybe a way to use setpoint shift group object or individual independent temperatures instead of deviating preset temperatures from comfort?

Otherwise, is there a read flag set by default for the comfort target temperature GO (4/2/63)? If not, does it respond correctly if you set the flag?

**Comment by DirkMu** [comment]
Hi.
Sorry for the late response. Unfortunately, there is no setpoint shift GO. The read flag is set be default. I assume there is no way change that behavior.

**Comment by farmio** [comment]
Hm... as a workaround you could configure `target_temperature_state_address` to the comfort address (same as `target_temperature_address`) and have a Sensor displaying the current mode setpoint ('4/2/64').

Otherwise it would require an additional attribute of the Climate device like "current_mode_target_temperature" or something like this that overrides https://github.com/home-assistant/core/blob/dev/homeassistant/components/knx/climate.py#L156-L159

**Comment by DirkMu** [comment]
To be honest, I think we cannot workaround this outside the thermostat. Since there is no GO, I assume, in order to adapt the target temp of mode e.g. 'night' you have to change to comfort, adapt the value, and go back to night.

**Comment by farmio** [comment]
My workaround proposal would create a "Comfort temperature climate entity". It would always show comfort temp regardless of current preset.

**Comment by DirkMu** [comment]
I am not sure if I get you correctly. Will this allow me to change e.g. the "night target temperature"? This is what I am attempting to achieve. 

I can change the target temp while preset mode comfort is active. However I cannot change the target temp of night while night is active. Using the physical thermostat this is possible. The physical thermostat allows me to overwrite the value (-2) defined in ETS. It is stored in the thermostat. E.g. comfort is 20 and night by default is 18. When I change the target temp while night is active the temperature of the preset mode night is changed. Comfort remains unchanged. As a result the shift differs from the value defined in ETS. 

Changing the target temp in HA while preset mode night is active will lead to a change of the comfort value. E.g. Comfort is 20, night is 18. Night is active and I decrease the temp by -0.5. HA thus sends 17.5 and the device responds with 15.5, because 17.5 is assumed to be the new comfort value which is decreased by 2.

**Comment by farmio** [comment]
No. It seems your controller just doesn't support changing individual mode (preset) temperatures from the bus.

**Comment by DirkMu** [comment]
Seems so. Thanks for helping.
