### ISSUE TITLE
Several xknx daemons

### ISSUE THREAD

**Issue by mralessio** [XKNX/xknx#1044]
For my use case I need to monitor more than one KNX/IP connections (separate lines) and periodically send the telegrams.
Is it possible to establish several tunneling connections to different KNX/IP interfaces with `deamon_mode=True` at the same time?
Thanks for help

**Comment by farmio** [comment]
Not sure if `daemon_mode` works with multiple connections. Just try it out. 
Otherwise you can just call `start()` and `stop()` for every of your XKNX instance in a custom function where you wait for sigint.

**Comment by mralessio** [comment]
Unfortunately, it doesn't. Next daemon will not start until the previous one has not finished. 
Not sure that just start / stop would work for me in the full scope, as I need to monitor connections constantly.

**Comment by farmio** [comment]
Daemon mode doesn't do anything else than calling start() and waiting for sigint. 
Have you put your instances in Tasks? That should not block...

**Comment by mralessio** [comment]
Thank you for the giving the idea. I just have started using Python recently for knx purposes. I will try to implement.
