### ISSUE TITLE
Missing DPT 9.009 Value Air Flow

### ISSUE THREAD

**Issue by rtreichl** [XKNX/xknx#1122]
Hello im Using HA and KNX and was just wondering why the DPT 9.009 is not pressent.
Is there a reason it is skipped?
If not can it be implemented easily?

![image](https://user-images.githubusercontent.com/8200744/210169859-e20598e9-94cf-4862-81a5-3abbcc01cb02.png)

Thanks and Bests
Richard

**Comment by farmio** [comment]
Hi 👋! 

We don't have all DPTs implemented (yet). There is no particular reason. 

It can be implemented quite easily. 

On the other hand there is not really anything special about it, so you may also just use `value_type = "2byte_float"`.

**Comment by farmio** [comment]
> If not can it be implemented easily?

@rtreichl do you want to do that? Here would be a good example https://github.com/XKNX/xknx/pull/397
