### ISSUE TITLE
Inverted DPT 5.001 Percentage values

### ISSUE THREAD

**Issue by TinusK** [XKNX/xknx#114]
As per xknx v0.8.2 all DPT 5.001 values are inverted. If GA with DPT 5.001 returns 0% then it is showed in HAss as 100%, 80% is showed as 20%, 100% as 0%. 

Regards,
Martijn

**Comment by TinusK** [comment]
I solved it by changing the following code in xknx/devices/remote_value_scaling.py

```
    def to_knx(self, value):
        """Convert value to payload."""
        if not self.invert:
            value = 100 - value
        return DPTArray(DPTScaling.to_knx(value))

    def from_knx(self, payload):
        """Convert current payload to value."""
        value = DPTScaling.from_knx(payload.value)
        if not self.invert:
            value = 100 - value
        return value
```
to
```
    def to_knx(self, value):
        """Convert value to payload."""
        if self.invert:
            value = 100 - value
        return DPTArray(DPTScaling.to_knx(value))

    def from_knx(self, payload):
        """Convert current payload to value."""
        value = DPTScaling.from_knx(payload.value)
        if self.invert:
            value = 100 - value
        return value
```

Per default, invert is set to false. Then if invert=true then value should be 100-value and not when invert=false :) So, I changed "if not self.invert" to "if self.invert"

Unfortunately I'm unfamiliar with git and don't know how to create a pull request. Maybe someone else could do this for me?

I tested it in my KNX configuration and all 'percentage' DPT5.001 are now showing the correct value.

Tinus

**Comment by TinusK** [comment]
Hmmm. It does however break my Cover position which are also reported in DPT5.001....

I really do not know what is going on here.... 

In ETS everything is reporting correctly in DPT5.001 but in HAss the values for a sensor are 100-value (20% is in HAss 80% asf.) But the cover positions are correct.... Changing remote_value_scaling to the above.... The sensor values are correct but my covers are not :(

**Comment by Julius2342** [comment]
@tinusk: are you only talking about scaling sensors?

**Comment by TinusK** [comment]
No, I just tried to solve it... Thought it was a problem in remote scaling but it then broke other dpt5.001 sensor values (e.g. cover position).
________________________________

**Comment by Julius2342** [comment]
@TinusK i pushed a change, may you try out?

**Comment by TinusK** [comment]
I really would.... but yesterday my test system crashed.... hope to have it up and running in the next couple of days! Sorry...

**Comment by TinusK** [comment]
OK, I tried it out.... It looks like it is working correctly now.... However, all my KNX Lights are not showing up anymore:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 268, in _async_add_entity
    yield from entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 251, in async_update_ha_state
    supported_features = self.supported_features
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/light/knx.py", line 159, in supported_features
    if self.device.supports_dimming:
AttributeError: 'Light' object has no attribute 'supports_dimming'

**Comment by TinusK** [comment]
I think I mixed up some versions.... Unfortunately I don't have a test machine available at the moment.... But sensor is displaying the correct Percentage values.

**Comment by Julius2342** [comment]
the lights problem is a version mismatch ...

**Comment by itineric** [comment]
Hi,

I do have this exact issue with home assistant.
I noticed it on the cover component and added an issue here: https://github.com/home-assistant/home-assistant/issues/11633
That was not a big deal back then, just set the invert the other way around. But now i am developing a percentage-based fan support for hassio. When i set the value to 25% my fan moves to 75%.
How can i know the xknx version used in my setup ? I may be able to test your dev.
