### ISSUE TITLE
ImportError: cannot import name 'GroupAddress'

### ISSUE THREAD

**Issue by Emenc** [XKNX/xknx#115]
I am exploring the examples. When I try 'example_value_reader.py' I get:

 from xknx import GroupAddress
ImportError: cannot import name 'GroupAddress'

What do I do wrong?

Thanks

**Comment by Julius2342** [comment]
This is most likely a version conflict between installed version and checked out version.

(in Version 0.8.0 we split up Address in GroupAddress and PhysicalAddress).

You might try to set PYTHONPATH to your checkout directory or try to upgrade xknx via pip ...

**Comment by Julius2342** [comment]
Were you able to fix this?

**Comment by Emenc** [comment]
Thanks for asking.

 

No, I did  not use it. I worked around is by using ‘bus_monitor’ 

 

Kind regards,

 

Mark Lins

 

 

Van: Julius Mittenzwei [mailto:notifications@github.com] 
Verzonden: zaterdag 3 maart 2018 19:02
Aan: XKNX/xknx <xknx@noreply.github.com>
CC: Emenc <mark@emence.be>; Author <author@noreply.github.com>
Onderwerp: Re: [XKNX/xknx] ImportError: cannot import name 'GroupAddress' (#115)

 

Were you able to fix this?
