### ISSUE TITLE
Sensor without value_type given is broken

### ISSUE THREAD

**Issue by buergi** [XKNX/xknx#121]
In the hass plugin sensor has an optional type, it once was, but now it is mandatory as RemoteValueSensor throws a ConversionError when no type is set.
In the old sensor.py there was a kind of fall back when no type was given:
```
        elif isinstance(self.state, DPTArray):
            return ','.join('0x%02x' % i for i in self.state.value)
        elif isinstance(self.state, DPTBinary):
            return "{0:b}".format(self.state.value)
```
Of course setting the parameter as mandatory solves the problem, however, I would prefer to have a similar generic solution as this, as there are hundreds of DPTs defined in the standard and only a very small subset is currently implemented. Such a solution allows using undefined data types in scripts or automation. For example, I used the above fallback in an appdaemon script to read a Dimming Type DPT 3.007 sensor from the bus which is now broken since my last update.

**Comment by farmio** [comment]
The value_type is intended to be mandatory. We have nearly all numeric DPTypes that are defined in the standard available as Sensor now. 
If you want to work with raw values from HA have a look at the knx_event event or the Knx.send service. 

As for DPT3 I agree that we should find a clean solution for this, but it should be more accessible than manually parsing binary values from within HA.
