### ISSUE TITLE
Non-standardised DP type explanation

### ISSUE THREAD

**Issue by milleroff** [XKNX/xknx#1212]
Hi.

I've found the following class in [dpt_hvac_mode.py](https://github.com/XKNX/xknx/blob/7542d975f66aff2811c00f83a1573a6a1d44bc55/xknx/dpt/dpt_hvac_mode.py):

```
class DPTControllerStatus(_DPTClimateMode[HVACOperationMode]):
    """
    Abstraction for KNX HVAC Controller status.
    Non-standardised DP type (in accordance with KNX AN 097/07 rev 3).
    Help needed:
    The values of this type were retrieved by reverse engineering. Any
    notes on the correct implementation of this type are highly appreciated.
    """

    SUPPORTED_MODES: dict[int, HVACOperationMode] = {
        0x21: HVACOperationMode.COMFORT,
        0x22: HVACOperationMode.STANDBY,
        0x24: HVACOperationMode.NIGHT,
        0x28: HVACOperationMode.FROST_PROTECTION,
    }
```

Regarding the asked help:

The correct implementation is shown on the page 139 of the product documentation of ["Jung LS 5194 KRM TS D" thermostat](https://downloads.jung.de/public/en/pdf/productdocumentation/en_5192KRMTSD_td_2022-06-10.pdf)

<img width="832" alt="screenshot 2023-03-01 22 19 28" src="https://user-images.githubusercontent.com/1090680/222256404-d86c0f66-ecb4-4541-8bb9-69cd8358008d.png">

**Comment by farmio** [comment]
Hi 👋! 
Right, currently it is only used for operation modes when "heating". You are welcome to update this to support the rest of its capabilities.
