### ISSUE TITLE
Home Assistant illuminance sensor shows absolutely wrong values (thousands of lux)

### ISSUE THREAD

**Issue by mikz** [XKNX/xknx#1287]
**Description of problem:**

- [ ] using xknx standalone
- [x] using Home-Assistant knx integration

**Version information:**
- xknx / Home-Assistant release with the issue: HAOS  10.3, HA Core 2023.6.2
- last working xknx / Home-Assistant release (if known):

**KNX installation:**

I have GIRA 222000 Presence Detector Mini and configured it as occupancy sensor. Now I want to expose the brightness sensor in Home Assistant. I've already exposed it to HomeKit through Thinka without problems. 

Here is the ETS configuration.

<img width="2048" alt="Screenshot 2023-06-23 at 9 17 34" src="https://github.com/XKNX/xknx/assets/154571/8f2617d7-1b8c-43ab-8a41-0dcc65c5bedc">

Here are values from the group monitor.
<img width="1133" alt="Screenshot 2023-06-23 at 9 19 17" src="https://github.com/XKNX/xknx/assets/154571/7b60fbf1-5614-4438-b325-6a6ad7987845">

Home Assistant reads it as thousands of lux, which is obviously wrong.
<img width="582" alt="Screenshot 2023-06-23 at 9 19 56" src="https://github.com/XKNX/xknx/assets/154571/d192cc03-a480-4f2b-9221-0c1539948164">

The current value is 297-318 lux. I configured Thinka to read the same group address and export it to homekit and it works right.
When I read the value in ETS it also responds correctly.

**Problem-relevant `configuration.yaml` entries (fill out even if it seems unimportant):**

```
sensor:
- name: "Living Room Light Sensor"
  state_address: "1/0/6"
  device_class: illuminance
  type: brightness
```

**Diagnostic data of the config entry (only when Home Assistant is used)**

**Traceback (if applicable):**

I'd be able to create a PR if I get some pointer where to look at.

**Comment by farmio** [comment]
Hi 👋! 
Use `type: illuminance`.  
`type: brightness` for an DPT 9 illuminance sensor is absolutely wrong 😉
See https://www.home-assistant.io/integrations/knx/#value-types

**Comment by mikz** [comment]
🤦 I see. There are two. Thanks!
