### ISSUE TITLE
Set KNX/IP gateway address

### ISSUE THREAD

**Issue by MaxXor** [XKNX/xknx#130]
Hello, how can I set an IP address for a KNX/IP gateway? It's not found automatically. Also does the telegram monitor support non-group telegrams?

**Comment by Julius2342** [comment]
just define a connection config:

https://github.com/XKNX/xknx/blob/master/xknx/xknx.py#L63

**Comment by marcor4** [comment]
Hi! How the connection config can be defined? Could you be a little bit more specific?

**Comment by farmio** [comment]
It could look like this:
```python
    xknx = XKNX()
    connection_config = ConnectionConfig(
        connection_type=ConnectionType.TUNNELING,
        gateway_ip="192.168.1.2", gateway_port=3671,
        local_ip="192.168.1.109")
    await xknx.start(connection_config=connection_config)
```

**Comment by marcor4** [comment]
I am currently trying the code listed in the previous message and it works:
`  xknx = XKNX()
    connection_config = ConnectionConfig(
        connection_type=ConnectionType.TUNNELING,
        gateway_ip="192.168.1.2", gateway_port=3671,
        local_ip="192.168.1.109")
    await xknx.start(connection_config=connection_config)
`

On the contrary, yaml file does not seem to work. I don't remember the error message, but it was about the fact that groups were not defined.

**Comment by marcor4** [comment]
This was my configuration yaml:

```python
connection:
    tunneling:
         host: '192.168.1.110'
         port: 3671
         local_ip: '192.168.1.103'
```

Now I am noticing that https://xknx.io/configuration uses `xknx:` instead of `connection:`. Is it making any difference?

**Comment by farmio** [comment]
https://xknx.io/home_assistant is using `xknx:` this is the Home-Assistant plugin. If you use xknx directly or pass a yaml file to xknx you will need `connection:`

If you get the current master from github (or wait til 0.9.5 is released) this configuration yaml should almost work. Almost because `host:` is the HA-plugin-term - for xknx this would be `gateway_ip:`; `port:` would be `gateway_port:`

**Comment by marcor4** [comment]
Yes correct. I posted the wrong yaml file (one of my attempts with the HA, which I am not using anymore). So with the newest version the xknx the following yaml shoud work:

```python
connection:
     tunneling:
          gateway_ip: '192.168.1.110'
          gateway_port: 3671
          local_ip: '192.168.1.103'
```

**Comment by farmio** [comment]
Exactly.
