### ISSUE TITLE
Make devices re-attachable

### ISSUE THREAD

**Issue by farmio** [XKNX/xknx#1352]
Currently the instantiation of an xknx Device object auto-attaches it to the xknx devices list.
https://github.com/XKNX/xknx/blob/a51e2b449f405cc27154b4401604b96959ee84be/xknx/devices/device.py#L45

If `Device.shutdown()` is called later, it is removed, its RemoteValues and Tasks are destroyed and it is essentially not re-usable.
https://github.com/XKNX/xknx/blob/a51e2b449f405cc27154b4401604b96959ee84be/xknx/devices/device.py#L56-L62

We should decouple the instantiation from starting and stopping tasks, so that we can stop and later re-use an instance of a Device  if we still have a reference. Like pausing a device.
- remove pending tasks
- remove callbacks (eg. `process()` for processing further telegrams)
- remove its RVs from StateUpdater
- maybe clear the state
- have a method to restart / reattach it to work again

In HA this would be needed eg. when entity_id was changed - the xknx device instance is created in `Entity.__init__()` but when an entity_id is changed, `async_remove_from_hass` and `async_added_to_hass` are called. Unfortunately there is no way to determine if the Entity object will be re-used in the `async_remove_from_hass` call. https://github.com/home-assistant/core/blob/89a9e6c6e842e7cf2265238d57ca011ed44d225e/homeassistant/components/knx/knx_entity.py#L46

Further, deactivating and reactivating an entity in HA currently restarts the whole integration. When we had reattachable devices, this wouldn't be necessary anymore. We could then just restart the xknx device and attach its callbacks. (This is probably not applicable to config changes - eg. from panel - since we need a new device instance then anyway).

Related issues
- https://github.com/home-assistant/core/issues/103116
- https://github.com/home-assistant/core/issues/82158

**Comment by Bingo2023** [comment]
I think I run into this problem. KNX was runing fine until some HA update caused problems then I installed some backup.. so went back & forth with HA-Versions.

Since than KNX is unusable. I see all the knx data in Groupmonitor.
But all enties disappeared/are empty.

Any idea of how to recover from this state?

**Comment by farmio** [comment]
@Bingo2023 Hi 👋! I don't think that your problem is related. 
 
This issue doesn't apply to HA restarts or integration reloads since a new xknx instance is initialized then. 
AFAIK in HA this issue is currently only applicable when changing an entities entity_id. 

Have a look at the logs - maybe they there is some hint about what's wrong in your installation.
