### ISSUE TITLE
Issue with dimming - Gira system

### ISSUE THREAD

**Issue by perara** [XKNX/xknx#136]
Hi,

I'm using Home assistant with the plugin to xknx.
I've defined the following:
 ```
groups:
    light:
        Gang_Nede_0:     {group_address_switch: '0/0/1', group_address_brightness: '0/1/1'}
```

But the dimming does not work. Yes, the addresses are OK.
VBUS reports the following when using the physical switch:

LPDU: BC 11 0B 01 03 E1 00 89 33 :L_Data low from 1.1.11 to 0/1/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 09
LPDU: BC 11 0B 01 03 E1 00 80 3A :L_Data low from 1.1.11 to 0/1/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00

While the home assistant dimmer reports this:

LPDU: BC FF FA 01 03 E2 00 80 CC EA :L_Data low from 15.15.250 to 0/1/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write CC
LPDU: BC FF FA 01 03 E2 00 80 56 70 :L_Data low from 15.15.250 to 0/1/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 56
LPDU: BC FF FA 01 03 E2 00 80 56 70 :L_Data low from 15.15.250 to 0/1/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 56
LPDU: BC FF FA 01 03 E2 00 80 0D 2B :L_Data low from 15.15.250 to 0/1/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 0D

There seems to be difference where the physical dimmer says (small) having more bits.
Is there a fix for this?

**Comment by perara** [comment]
Sorry, wrong light in the configuration file. Yes it is correct, having 0/1/3 as the group_address_brightness set to 0/1/3

i noticed:
LPDU: BC 11 0B 01 03 E1 00 89 33    <-- Switch
LPDU: BC FF FA 01 03 E2 00 80 56 70 <-- xknx

There is 2 more bits there at the end. Ive tried several other dimmers as well, and all of them have the same problem

**Comment by moustic999** [comment]
OK the issue is quite easy ! 
GIRA use 1-byte obejct for dimming where almost all others use a 2-bytes object.
xknx has been implemented to send value via a 2-bytes object.

**Comment by perara** [comment]
Would it be possible to implement a bool to support 1bit systems?

**Comment by farmio** [comment]
@perara can you provide more information on your actuator model and the communication object linked to the group address?
I think you were trying to use a group address for stepwise dimming (4 bit) with the `group_address_brightness` function which is used with absolute dimming (1 byte) group addresses.
If this is true check if your actuator supports both relative (stepwise) and absolute (percent) dimming and set the absolute dimming communication object to a new group address to use with xknx `group_address_brightness` (and maybe a seperate group address for the status communication object to `group_address_brightness_state`).
