### ISSUE TITLE
DPT decoding

### ISSUE THREAD

**Issue by lukaszzyla** [XKNX/xknx#1419]
**Description of problem:**

Integration is great, but several DPT are not being translated resulting in payloads in hex not being translated to values.
<img width="698" alt="image" src="https://github.com/XKNX/xknx/assets/36972413/2432d2eb-5a2d-4cfa-884e-a4cb411e0a8f">

This doesn't seem to affect gira 222 500 motion sensor which reports fine but does affect MDT SCN IP100.03 router which sends data properly (and also includes proper DPT in payload) but integration does not translate it to vakues:
<img width="669" alt="image" src="https://github.com/XKNX/xknx/assets/36972413/2e627bb8-dc0d-4603-af9c-70939b20924d">

- [ ] using Home-Assistant knx integration
ETS 6 with latest apps.

**Comment by farmio** [comment]
Hi 👋! 

In group monitor, as well as in device trigger, knx_event, knx.send etc. only those DPT listed in HAs sensor documentation are en/decoded. 

For date/time you can use a corresponding entity in HA to read or write.

**Comment by lukaszzyla** [comment]
I have found the docs on DPT - thank you.
Anyway it is great to have KNX support in HA.

**Comment by lukaszzyla** [comment]
everything works as expected.
