### ISSUE TITLE
Add DPT 9.020 (Voltage) a 2 byte float

### ISSUE THREAD

**Issue by magenbrot** [XKNX/xknx#142]
Hi,

My KNX power supply is able to collect some metrics like power, voltage and current. It seems that "voltage" isn't supported by xknx and HA yet, as it isn't mentioned in the home-assistant documentation. I've added it manually and it works. I'll send an PR later if anyone could confirm that voltage really isn't supported right now and I just did not see it ;)

best regards
magenbrot

**Comment by Julius2342** [comment]
I think voltage is not yet included ... so a PR is highly appreciated!

(mhmmjm, Magenbrot :-) )

**Comment by Julius2342** [comment]
I also have a (half-working) (refactoring)[https://github.com/XKNX/xknx/pull/127] of the DPT's to make things more flexible - which i started earlier this year, and somehow lost focus. Depending on how complex your change is, we might consider putting this inside this branch. And i could take the chance to start working on this again :-)

**Comment by magenbrot** [comment]
the change is rather small, please review this PR #143

**Comment by magenbrot** [comment]
new PR #146, replacing the other.

**Comment by farmio** [comment]
It is merged now and 9.020 Voltage is in the HA documentation now I think this issue can be closed.
