### ISSUE TITLE
KNX.send DPT 20.102

### ISSUE THREAD

**Issue by Andi1980** [XKNX/xknx#1427]
Hi,

actually I try to set up a HA-automation, setting comfort/night mode. It should by triggered by time. Only sending 1 or 3 to the group address does not effekt the HVAC mode. When I use knx.send to DPT:20.102 i got following error:

_type '20.102' is not a valid DPT identifier for DPTBase. for dictionary value @ data['type']. Got 'execute_script'_

YAML is:
_service: knx.send
metadata: {}
data:
  address: x/x/x
  payload: 1
  type: "20.102"_

Thank You

Andi

**Comment by farmio** [comment]
Hi 👋! 
Only the values listed here are valid for `type`: https://www.home-assistant.io/integrations/knx/#value-types

If you want to send a raw 1-byte `1`, you'd have to use a list - so `payload: [1]`. See documentation https://www.home-assistant.io/integrations/knx/#send
