### ISSUE TITLE
Startup Warnings  with Climate component on HA

### ISSUE THREAD

**Issue by resoai** [XKNX/xknx#148]
It look  like every time HA starts, xknx raises a warning for each climate entity as follows:

```
Could not read value of <Climate name="Master Bathroom" temperature="GroupAddress("4/6/10")/None/<DPTArray value="[0xd,0x8]" />/25.76"  target_temperature="GroupAddress("4/5/10")/None/<DPTArray value="[0xc,0x1a]" />/21.0"  setpoint_shift="GroupAddress("3/3/10")/GroupAddress("4/3/10")/<DPTArray value="[0x0]" />/0" setpoint_shift_step="0.5" setpoint_shift_max="6" setpoint_shift_min="-6" group_address_operation_mode="GroupAddress("3/1/10")" group_address_operation_mode_state="None" group_address_controller_status="None" group_address_controller_status_state="GroupAddress("4/0/10")" /> 3/1/10
```

It looks like we need to skip checking operation_mode_state if controller_status_state is defined.

**Comment by resoai** [comment]
Sadly I can’t check it since I’m running Hassio

**Comment by resoai** [comment]
Would you be able to create a PR bumping the version?

**Comment by Julius2342** [comment]
I bumped it last week, and I got some weird warnings. i want to investigae these before moving on :-)

**Comment by rsterrenburg** [comment]
@Julius2342 any plans on bumping the version or still getting the weird warnings?

**Comment by Julius2342** [comment]
I tried it, and already found some bugs.

At the moment the syncing does not work. Will have a look at it asap. But it is progressing (slowly).

**Comment by resoai** [comment]
I'm afraid I'm still getting warning messages.

**Comment by Dudu67** [comment]
Same here :
```
Log Details (WARNING)
Tue Dec 11 2018 08:22:16 GMT+0100 (heure normale d’Europe centrale)

Could not read value of <Climate name="Sensor.clim_ch3.climate" temperature="None/GroupAddress("3/1/7")/<DPTArray value="[0x7,0xbc]" />/19.8"  target_temperature="GroupAddress("3/2/7")/None/None/None"  setpoint_shift="None/None/None/None" setpoint_shift_step="0.5"
setpoint_shift_max="6" setpoint_shift_min="-6"
group_address_operation_mode="GroupAddress("3/4/10")" group_address_operation_mode_state="GroupAddress("3/4/10")" group_address_controller_status="None" group_address_controller_status_state="None" group_address_controller_mode="None" group_address_controller_mode_state="None" group_address_on_off="None/None/None/None" /> 3/4/10
```

And this append cyclically every hour.
By looking at this error I see that there is a "group_adress_on_off" paramater that is not documented in the climate component (and by the way not implement in the TileBoard @resoai).
For the moment i map a switch on this group to be able to switch on/off the HVAC unit, but it will be better to be able to call the climate.turn_on or climate.turn_off from home assistant.

Olivier

**Comment by farmio** [comment]
Hm 🤔. Seems related to #120

**Comment by resoai** [comment]
So, with HA 0.90 I'm afraid I'm still getting warning messages, although I've now started to receive separate ones for "mode":

```
Could not read value of <Climate name="AV room" temperature="None/GroupAddress("4/6/2")/<DPTArray value="[0xc,0x4e]" />/22.04"  target_temperature="None/GroupAddress("4/5/2")/<DPTArray value="[0xc,0x1a]" />/21.0"  setpoint_shift="GroupAddress("3/3/2")/GroupAddress("4/3/2")/<DPTArray value="[0x0]" />/0" setpoint_shift_step="0.5" setpoint_shift_max="6" setpoint_shift_min="-6" group_address_on_off="None/None/None/None" /> 3/1/2

```

```
Could not read value of <ClimateMode name="AV room Mode" group_address_operation_mode="GroupAddress("3/1/2")" group_address_operation_mode_state="None" group_address_controller_status="None" group_address_controller_status_state="GroupAddress("4/0/2")" group_address_controller_mode="None" group_address_controller_mode_state="None" /> 3/1/2
```

The config I'm using for climate is as follows:

```
- platform: knx
  name: AV room
  temperature_address: 4/6/2
  target_temperature_state_address: 4/5/2
  setpoint_shift_address: 3/3/2
  setpoint_shift_state_address: 4/3/2
  operation_mode_address: 3/1/2
  controller_status_state_address: 4/0/2
```

Please note that I have to use `controller_status_state_address` because I have Jung room controllers and they handle operation modes differently. It was only thanks to @Julius2342 that we have discovered it last year. Do you guys know what could be the source of those warnings? I'm afraid setting `rate_limit` did not help.

**Comment by resoai** [comment]
Bump

**Comment by moustic999** [comment]
You are missing the : operation_mode_state_address ??

**Comment by resoai** [comment]
> You are missing the : operation_mode_state_address ??

I have to use `controller_status_state_address` instead of `operation_mode_state_address` because I have Jung room controller which reports status in different format (AN 097/07).

**Comment by Julius2342** [comment]
@resoai : yes, on your devices reading and writing is done via different "types" of addresses. For whatever reason.

**Comment by resoai** [comment]
Could this be the reason of the warnings?

**Comment by Julius2342** [comment]
@resoai : may you log telegrams and past which exact read-telegram xknx is sending out directly before you see this message?

**Comment by farmio** [comment]
There are even more issues with controller_status and controller_mode actuators. See https://github.com/home-assistant/home-assistant/issues/21737
