### ISSUE TITLE
Hello, I encountered some issues while using homeassisant regarding my DALI dual color temperature bulb.

### ISSUE THREAD

**Issue by frncistic** [XKNX/xknx#1558]
**Description of problem:**

 "Hello, I have encountered some issues while using Home Assistant with my DALl dual color temperature bulb. 
The problem lies in the connection between my dual color temperature light bulb and Apple Home through Home Assistant.
 I am controlling it to switch scenes via Apple Home, which involves simultaneous control of both brightness and color temperature. However, I have noticed that it does not function as expected, occasionally getting stuck in either the color temperature or brightness settings. Interestingly, when I used Node-RED to control the scene switching with a dual color temperature light bulb, everything worked normally.
 This leads me to believe that there might be an issue with the order in which instructions are sent in ETS."
![Snipaste_2024-08-29_11-36-53_1](https://github.com/user-attachments/assets/c7455d24-33b3-43b2-a88b-b3696fa5fb84)

- [ ] using xknx standalone
- [✓] using Home-Assistant knx integration

**Version information:**
- xknx / Home-Assistant release with the issue: 2024.8.3
- last working xknx / Home-Assistant release (if known): none

**KNX installation:**

**Problem-relevant `configuration.yaml` entries (fill out even if it seems unimportant):**

**Diagnostic data of the config entry (only when Home Assistant is used)**

**Traceback (if applicable):**

**Comment by frncistic** [comment]
![image](https://github.com/user-attachments/assets/929e4a78-4671-4d00-a3aa-46a1c6beea32)

**Comment by farmio** [comment]
Hi 👋! 
Unfortunately, from your screenshots, I can't tell what you mean by "an issue with the order in which instructions are sent in ETS". Is this using a HA scene containing multiple light entities?

It looks like first brightness, then color temperature values are sent to the bus - for multiple devices consecutively. Which seems fine to me. 
There doesn't seem to be any status update telegrams from the DALI device though - that would maybe help identify the issue.

**Comment by frncistic** [comment]
yes,i using a HA scene containing multiple light entities
  If I use HA scenes to control multiple light entities, it will be sent in the form of the top on the picture , which will cause the scene of brightness or temperature color to be different. for example, I set the brightness of 100, maybe this light is interrupted at 20 brightness, but when I use nodered manual, i delay the brightness of all lights and adjust the color temperature. Therefore The state will be changed according to our scene
  Therefore, when the lighting entity is controlled through HA, can you first send the brightness value of all light entities and then send the color temperature value of all light entities, which will not cause the actual light brightness and scene settings of the scene settings inconsistencies.

**Comment by frncistic** [comment]
![（产品分享） DALI 网关切换场景问题_3_Cherio_来自小红书网页版](https://github.com/user-attachments/assets/e2876bea-d141-4722-91ab-ef166a196f4f)
![（产品分享） DALI 网关切换场景问题_4_Cherio_来自小红书网页版](https://github.com/user-attachments/assets/a7526877-74b0-466f-850e-8315cf764fd0)

**Comment by farmio** [comment]
> Therefore, when the lighting entity is controlled through HA, can you first send the brightness value of all light entities and then send the color temperature value of all light entities

No, we can't do that. From an integration point of view, a call to a group of entities isn't distinguishable from multiple single calls (maybe manual etc.). So we don't know about the group / HA scene. 

Tbh, to me this sounds like an issue of the DALI actuator. Imho it should be able to process multiple telegrams like that - maybe there is some configuration to set.

**Comment by frncistic** [comment]
Thank you very much for your help in trying to replace dali gateway
