### ISSUE TITLE
New Illuminance Type

### ISSUE THREAD

**Issue by auredor** [XKNX/xknx#201]
Hello,

It would be interesting to create a new type of data for HA. This new type would be based on illuminance value coming from KNX sensor but with an additionnal postprocessing.

The purpose is to get some values that are more meaningfull to read/use.  Illuminance (lx) is not linear. There's quite a huge variation of Lux for a small increase of "perceived" brightness change :
[Understanding and Interpreting Lux Values](https://docs.microsoft.com/en-us/windows/desktop/sensorsapi/understanding-and-interpreting-lux-values)

So, in order the get a better feeling of the light in a given room, it would be more interresting to return a

>  log10 (lux Value) / 5.0

We would then get a linear relation between what is sensed and the light in the room.
We could call the new type something like **NormalizedLight** with **Loglx** as Unit? But I don't know how HA can handle that unit.

Thank you.

**Comment by farmio** [comment]
Hello!

To accomplish getting a new data type in HA I would suggest opening an issue at https://github.com/home-assistant/home-assistant . This way every HA compatible device could use this (I'm thinking something like metric/imperial unit_system configuration transparent to HA devices). If it was xknx only there would be no   interaction with devices outside of knx.

If you just want to fiddle with it on your instance a [template sensor](https://www.home-assistant.io/components/template/#change-the-unit-of-measurement) would probably be the way to go.
