### ISSUE TITLE
Add DPTs

### ISSUE THREAD

**Issue by daniwebCH** [XKNX/xknx#213]
Could you please add the following types?
- 5.003 angle
- 9.022 power density w/m2
- 7.001 pulses

thanks

**Comment by farmio** [comment]
5.003 is already merged and will be available with the next release.
9.022 is just a 2 byte float with a unit. You can use a sensor with the generic type 'DPT-9' and override the unit.
7.001 is already available under the not-so-obvious sensor type name '2byte_unsigned'.
