### ISSUE TITLE
Add new DPT value types

### ISSUE THREAD

**Issue by farmio** [XKNX/xknx#236]
Hi 👋

Some DPT value types are still missing in xknx. 
Help us to support all datapoint types by adding some missing definitions. There is a great example of how its done in #223 or #208 .

Missing DPTs are for example:

- [ ] 7.003 - 7.012
- [ ] 8.003, 8.004
- [ ] 9.008, 9.010
- [ ] 9.021 - 9.028

and some more.

**Comment by eXtenZy** [comment]
I got the knx specification from knx.org. I'll have a go.
