### ISSUE TITLE
Wrong calculation of position within shutter/travelcalculator

### ISSUE THREAD

**Issue by Julius2342** [XKNX/xknx#24]
twistermcneal writes:

> es gibt aber noch einen Bug. Wenn ich von der max/min Position eine neue Position setze dann wird manchmal eine falsche aktuelle Position errechnet!
> Habs aber noch nicht gefunden.
> 
> Scheint aber immer dann zu passieren wenn man die Jalousie komplett auffährt ohne stopp zu betätigen oder eine Position anzufahren...

**Comment by twistermcneal** [comment]
Nachdem ich die pyc Dateien gelöscht habe sind momentan keine Fehler vorhanden!
Trigger von Bus Seite muss noch implementiert werden!

**Comment by Julius2342** [comment]
Könntest du ein Ticket hierzu aufmachen bitte?

Dieses Ticket schließe ich dann oder?
