### ISSUE TITLE
ImportError: No module named 'xknx.telegram'

### ISSUE THREAD

**Issue by Holland1** [XKNX/xknx#248]
Hi,

I'm trying to run a few examples from the examples section. Most run fine, and return read values, e.g. example_sensor.py and example_gatewayscanner.py

But the examples which call the xknx.telegram module (e.g  example_value_reader.py and example_telegram_monitor.py) fail with the following error;
ImportError: No module named 'xknx.telegram'

Maybe someone can help to figure out what went wrong.

Thanks

- [ x] using xknx standalone version 0.11.2
- [ ] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue:
- last working xknx / Home-Assistant release (if known):

**KNX installation:**

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

**Traceback (if applicable):**

**Comment by farmio** [comment]
We have moved some files recently in #232 . This change has not been in a release yet.
- You could use the current master instead of 0.11.2 or
- have a look at the examples before the change: https://github.com/XKNX/xknx/tree/0.11.2/examples
