### ISSUE TITLE
Cover position query causes Error while syncing device: <CouldNotParseTelegram description="payload invalid"

### ISSUE THREAD

**Issue by tobiasneumann42** [XKNX/xknx#310]
**Description of problem:**
using somfy KNX 510i current position of cover returns error. ETS shows status group address as fully open with value 100,32 DPT Type 2 byte.
Home assistant reports error 2020-06-21 12:24:44 ERROR (MainThread) [xknx.log] Error while syncing device: <CouldNotParseTelegram description="payload invalid" device_name="OG_shutter_hall" group_address="3/0/52" payload="<DPTArray value="[0x18,0x0]" />"/>

somfy 510i reports, 100 as completely closed and 0 as open bellow configuration for cover including the invert_position parameter set to true. 

cover:
  - platform: knx
    name: "OG_shutter_hall"
    move_long_address: '3/0/22'
    move_short_address: '3/0/23'
    position_address: '3/0/24'
    position_state_address: '3/0/52'
    invert_position: true

- [ ] using xknx standalone
- [ x] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: Home Assistant 0.111.3
- last working xknx / Home-Assistant release (if known):

**KNX installation:**
 
![Screen Shot 2020-06-21 at 13 35 47](https://user-images.githubusercontent.com/22684101/85223671-de22b580-b3c4-11ea-9276-4a211b3b897a.png)

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

**Traceback (if applicable):**

**Comment by tobiasneumann42** [comment]
![Screen Shot 2020-06-21 at 13 39 40](https://user-images.githubusercontent.com/22684101/85223686-f2ff4900-b3c4-11ea-985f-166d7074d408.png)

**Comment by tobiasneumann42** [comment]
`cover:
  - platform: knx
    name: "OG_shutter_hall"
    move_long_address: '3/0/22'
    move_short_address: '3/0/23'
    position_address: '3/0/24'
    position_state_address: '3/0/52'
    invert_position: true`

**Comment by farmio** [comment]
Postition and it's State is expected to be DPT5. Maybe you can set up your actuator to report in this format.

**Comment by tobiasneumann42** [comment]
don't think so (unless I am missing something obvious), the actuator doesn't allow to specify the data type... 

states Datatype: not defined and there is no option where I can set anything there. 

![Screen Shot 2020-06-21 at 15 58 07](https://user-images.githubusercontent.com/22684101/85226573-7aa28300-b3d8-11ea-863e-c44546af9013.png)

so position should always be DPT5 independent of the actuator manufacturer ? Was wondering if there would be a way to adjust the cover code to deal with different formats, in case this is not a generally accepted standard for all blinds/covers.

**Comment by farmio** [comment]
At least I have never seen this as 2byte Float. What can you select at "Datentyp"? Nothing?

You can for sure adjust the code to deal with this format. Here is a starting point: https://github.com/XKNX/xknx/blob/4a80c75b2448bca0ee98bfb6845fdc00f8ef6e80/xknx/devices/cover.py#L62
You can exchange RemoteValueScaling with eg. RemoteValueSensor

**Comment by spacegaier** [comment]
> 
> 
> At least I have never seen this as 2byte Float. What can you select at "Datentyp"? Nothing?

I just checked mine (brand "Warema") and can confirm they are also 1 Byte = `DPT 5.*`. The same holds true for all actuators that a quick search revealed online.

**Comment by farmio** [comment]
Also the Common visualizations (Gira G1 etc) expect DPT5. Maybe talk to the manufacturer of your actor about it. 
As a workaround you can use a simple logic to convert 2byte float to DPT5. This is also possible in HA. Define a sensor for DPT9 and expose its value as "percent" to a different GA. Use this GA for the Cover.
