### ISSUE TITLE
Add new Device to xknx.devices automatically

### ISSUE THREAD

**Issue by farmio** [XKNX/xknx#337]
Should we add a new Device to xknx.Devices on init? Currently newly created devices have to be added manually to receive incoming telegrams.
https://github.com/XKNX/xknx/blob/fb622f76f2e8b8de0454f94558b16a88c6655a33/xknx/core/telegram_queue.py#L144

```
xknx = XKNX()
sensor = Sensor(xknx, ...)
xknx.devices.add(sensor)
```
I'd like to remove this boilerplate and call `xknx.devices.add(self)` in `Device.__init__()` - and remove it in `__del__()`

**Comment by marvin-w** [comment]
Hmm, we also use this boilerplate in the HA plugin and I honestly like it there, but I get your point.

**Comment by farmio** [comment]
I think we would have to just drop this line then.
https://github.com/XKNX/xknx/blob/fb622f76f2e8b8de0454f94558b16a88c6655a33/home-assistant-plugin/custom_components/xknx/__init__.py#L159

**Comment by marvin-w** [comment]
I don't think so. There is also one reference in the factory.py when creating the climate. So go ahead if you want :-)
