### ISSUE TITLE
Polling Group Address

### ISSUE THREAD

**Issue by twistermcneal** [XKNX/xknx#34]
In a KNX system you dont have to poll group addresses .... each client sends is state if changed or periodically.
In a large system you will getting problems when you poll all groups

**Comment by Julius2342** [comment]
See your point.

I found it pretty useful to do this at the beginning, to have the current state in HASS ...

**Comment by Julius2342** [comment]
What about requesting all at the beginning (e.g. with lower throughput) and then only request group addresses which haven't been updated for a long time?

**Comment by twistermcneal** [comment]
in my case this leads to bus heavy and i never get a answer ... yes i think thats a possibility

**Comment by Julius2342** [comment]
i had a sleep within each request within the update loop, probably this got lost while refactoring

**Comment by Julius2342** [comment]
may you increase the value of "sleep_during_devices" within stateupdater.py ?

**Comment by twistermcneal** [comment]
think 0.5 is a good value i have 130 group addresses so it still runs :) but looks good

**Comment by Julius2342** [comment]
May you make a PR for the increased values?

**Comment by Julius2342** [comment]
with 0cee1e0d72882d7ea45d1463f1f7c426d5584195 the syncing is now synchronous, which means the next device is polled after the answer of the last device was received.

so no sleep during devices is needed.

**Comment by Julius2342** [comment]
i also increased the time during complete refetches. It is now fetched once per hour.
