### ISSUE TITLE
Merge all integration documentation to a single integration page

### ISSUE THREAD

**Issue by marvin-w** [XKNX/xknx#356]
As pointed out in https://github.com/home-assistant/home-assistant.io/pull/14350 we should merge all the docs into a single page.

**Comment by farmio** [comment]
Wow, this page is going to be looooooong. 🤦

**Comment by marvin-w** [comment]
Yep! I hope there will be at least some kind of ToC.

**Comment by marvin-w** [comment]
HA did this for us.

If there is a contest about the longest HA documentation page we are likely gonna win it :-D.
