### ISSUE TITLE
XKNX along Domoticz?

### ISSUE THREAD

**Issue by RicardP** [XKNX/xknx#389]
Hi Folks! 
I am on Domoticz, but since long time missing KNX integration/plugin. Even the list of other plugins is long no sign of KNX... However I am sure there is a lot of Users (maybe not so many Developers...) that would be very glad for KNX integration.
In Domoticz there is normally two ways of adding support for other equipment, protocol, standards; Built in (C++ I think) and Python Plugin directory.
Could you estimate the work for XKNX-Domoticz adaption, or is this not realistic?
I am sorry to tell I am not into software development and wont be able to contribute, in that way.

Thanks in advance!

Best regards,
Ricard

**Comment by marvin-w** [comment]
Hey,

I personally don't know that system but from a first glance it looks very similar to Home Assistant - just a lot smaller.

From what I know we do not plan to add support for additional smart home systems anytime soon. We would accept pull requests though.

I assume Domoticz is kind of similar to home assistant so you might want to check out the custom component within xknx for a starting point.

Feel free to join our discord if you have further questions.
