### ISSUE TITLE
Adjust workflow to update version to <RELEASE_VERSION>

### ISSUE THREAD

**Issue by marvin-w** [XKNX/xknx#400]
I don't really want to bother adjusting the version manually before each release. Instead this should be commited automatically - the resulting tag should reside on that commit then.

General idea:

Implement a new manual workflow that does the following:

* Commit new version
* Release prerelease

**Comment by farmio** [comment]
So the version number is generated automatically? Could that distinguish between major and minor version changes?

**Comment by marvin-w** [comment]
No, we still set the version manually on release. But maybe there is some kind of interception to bump the version in our code before that.

**Comment by farmio** [comment]
Ah. So you want to change the content of `__version__.py` on a release. 
Sounds nice!
We could then even append "beta" or anything after release so the version is marked as working branch version.
