### ISSUE TITLE
Griesser non-standard datapoint

### ISSUE THREAD

**Issue by couilloux** [XKNX/xknx#401]
Hi, 

I use a lot of [Griesser products](https://www.griesser.ch/fr/produits/automatismes/knx/knx) and those products use a non-standard datapoint based on a 6 bytes encoding. See the datapoint description.
[238-10755_10757-13_Griesser Object__d.pdf](https://github.com/XKNX/xknx/files/5241012/238-10755_10757-13_Griesser.Object__d.pdf)

I would like to know if it is possible with xknx to read the raw data of this 6 bytes encoding? I can do the translation of the data on my side.

Any suggestion ?

Julien

**Comment by farmio** [comment]
In HA you can use knx_event (see fire_event attribute description in HA docs) to get raw data. 
In xknx you could define a callback in TelegramQueue (or maybe UDPClient).
