### ISSUE TITLE
KNX Weather entity payload error for air pressure

### ISSUE THREAD

**Issue by DirkMu** [XKNX/xknx#405]
**Description of problem:**
I set up the new weather entity. For the air pressure the HA log shows an error due to an invalid payload. 

- [ ] using xknx standalone
- [X] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 0.13.0

**KNX installation:**
Jung Weather Station 2225 WSU
- communication object: Air Pressure DPT 9.006
![image](https://user-images.githubusercontent.com/53949754/93705737-df789100-fb1f-11ea-8c3a-058d1cefed00.png)

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

````
- name: 'Dach'
  address_temperature: '6/5/11'
  address_brightness_south: '6/5/6'
  address_brightness_west: '6/5/7'
  address_brightness_east: '6/5/5'
  address_wind_speed: '6/5/0'
  address_rain_alarm: '6/5/37'
  # address_frost_alarm: "7/0/6"
  address_wind_alarm: '6/5/29'
  # address_day_night: "7/0/8"
  address_air_pressure: '6/5/13'
  address_humidity: '6/5/12'
  expose_sensors: False
  sync_state: True
````

**Traceback (if applicable):**
```
2020-09-19 10:35:51 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/xknx/remote_value/remote_value.py", line 151, in read_state
    await self.process(telegram)
  File "/usr/local/lib/python3.8/site-packages/xknx/remote_value/remote_value.py", line 92, in process
    raise CouldNotParseTelegram("payload invalid",
xknx.exceptions.exception.CouldNotParseTelegram: <CouldNotParseTelegram description="payload invalid" device_name="Dach" feature_name="Value" group_address="6/5/13" payload="<DPTArray value="[0x6c,0xad]" />"/>
```

**Comment by marvin-w** [comment]
Whoops. I accidentally made the pressure of type DPT 14.058 (4 byte pressure) instead of DPT 9.006 (2 byte pressure). 

I'll fix this.
