### ISSUE TITLE
Update entity_id for a group

### ISSUE THREAD

**Issue by mag2bue** [XKNX/xknx#423]
**Description of problem:**

- [x ] using Home-Assistant knx plugin

**Version information:** 0.115.2

**KNX installation:**

homeassistant.update_entity is not working with a group only directly  with the entity_id.

e.g. 

entity_id: group.covers is not working  

entity_id: cover.room1 works

**Comment by marvin-w** [comment]
Groups are a home assistant concept and are in no way related to XKNX. Please file your issue in the home assistant repo or ask in their #support channel if they can help you :).

It would probably help to know your use case too.

**Comment by mag2bue** [comment]
OK, Thanks!
