### ISSUE TITLE
Change switch class to binary_sensor

### ISSUE THREAD

**Issue by andreasnanko** [XKNX/xknx#43]
Since we need switch as actor class it would be useful to change the class to binary_sensor.
Probably we can bundle it to a global sensor class for different types of sensors.

**Comment by Julius2342** [comment]
I moved:

* Switch -> BinarySensor
* Outlet -> Switch
* Sensor (with type binary) -> BinarySensor

The disadvantage is, that all switches (as in the white devices in the wall to switch on the light :-)  ) now show up in the Sensors section within HASS ...
