### ISSUE TITLE
DPTBase.transcode should not accept floats

### ISSUE THREAD

**Issue by marvin-w** [XKNX/xknx#452]
We should not allow converting floats into a DPT and instead use strings (which is already supported).

See #447

**Comment by farmio** [comment]
We should also change the string parser. Trailing zeros are not parsed now - eg. "12.120" is interpreted as (12, 12) because it is converted to float.

**Comment by marvin-w** [comment]
We could also outsouce the transcoder in an extra class. IMHO it shouldn't belong to DPTBase.
