### ISSUE TITLE
Feature request: add the "ignore_internal_state" property to "Sensors" the same way it works already for "Binary Sensors"

### ISSUE THREAD

**Issue by kalhimeo** [XKNX/xknx#465]
Hi,

In the last release the property "ignore_internal_state" was added to the knx "binary sensor", and it would be great to have this property for knx "sensors" as well.

For example I am using a sensor with type "scene_number" together with an automation in order to execute some actions within HA when a knx scene number is called, but if the same scene is called two times without any other scene number in between, the value of the HA sensor state is not changed and the automation is not called again.

Note : the KNX scene entity is no help in this case as its state in HA does not change when triggered (it stays on "scening") and is only used the other way around (make HA to trigger a KNX scene).

Thank you very much in advance !

**Comment by farmio** [comment]
I like the idea. For now as a workaround you can use the HA event fired by the knx integration `knx_event`. For this you will need to configure 'fire_event' and 'fire_event_filter' 
See https://www.home-assistant.io/integrations/knx/ (we should document this better 😶)

**Comment by kalhimeo** [comment]
Hi farmio, thank you for the suggestion, that would make the trick as well.
At the moment I added an extra action at the end of my automation in order to trigger a dummy scene number on the KNX bus. The state of the sensor entity is then "reset" to this dummy number and ready to be triggered when the target scene number is activated again.

**Comment by marvin-w** [comment]
Thanks! We will proceed here once we have time for it :-D. I'll tag this as Hacktoberfest, maybe someone wants to do it :)

**Comment by kalhimeo** [comment]
Thank you marvin :-)

**Comment by kalhimeo** [comment]
Thank you very much marvin !
