### ISSUE TITLE
GroupValueRead Error

### ISSUE THREAD

**Issue by sagitt** [XKNX/xknx#474]
**Description of problem:**

- [ ] using xknx standalone
- [X] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 0.116.4
- last working xknx / Home-Assistant release (if known): 0.114.X

**KNX installation:**

I have accesso to ets, but i (won't) can't write project myself on devices
ITF KNX\IP weinzierl

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

I have an energy meter and covers (blinds and shutters).
I configured all in the same way.

My energy counter have some values like image below, start from 7/0/0 and end with 7/0/5
Now, as below error, only from /0/3 to 0/5 show error. Configuring it with "false" sync_state make it not working.
The same happen with blinds % position. works very well with all shutters, but not with blinds that have the same configuration and works with the same hardware module. this have sync_state configured to "init" to show it only when starts and change.

```
    - name: 'Energia [Potenza Attiva]'
      state_address: '7/0/0'
      sync_state: true
      type: 'power'
    - name: 'Energia [Potenza Reattiva]'
      state_address: '7/0/1'
      sync_state: true
      type: 'electric_potential'
    - name: 'Energia [Tensione]'
      state_address: '7/0/2'
      sync_state: true
      type: 'electric_potential'
    - name: 'Energia [Corrente]'
      state_address: '7/0/3'
      sync_state: true
      type: 'electric_current'
    - name: 'Energia [Fattore Di Potenza]'
      state_address: '7/0/4'
      sync_state: true
      type: 'powerfactor'
    - name: 'Energia [Frequenza]'
      state_address: '7/0/5'
      sync_state: true
      type: 'frequency' 

    # Cucina
    - name: 'Stato Tapparella [Cucina]'
      state_address: '2/2/0'
      sync_state: 'init'
      type: 'percent'
    # Soggiorno
    - name: 'Stato Tapparella [Soggiorno]'
      state_address: '2/2/1'
      sync_state: 'init'
      type: 'percent'
    # Camera 3
    - name: 'Stato Tapparella [Camera 3]'
      state_address: '2/2/2'
      sync_state: 'init'
      type: 'percent'
    # Bagno
    - name: 'Stato Tapparella [Bagno]'
      state_address: '2/2/3'
      sync_state: 'init'
      type: 'percent'
    # Camera 2
    - name: 'Stato Tapparella [Camera 2]'
      state_address: '2/2/4'
      sync_state: 'init'
      type: 'percent'
    # Camera 1
    - name: 'Stato Tapparella [Camera 1]'
      state_address: '2/2/5'
      sync_state: 'init'
      type: 'percent'


    - name: 'Stato Tendone 1 [Balcone]'
      state_address: '8/2/0'
      sync_state: 'init'
      type: 'percent'
    - name: 'Stato Tendone 2 [Balcone]'
      state_address: '8/2/1'
      sync_state: 'init'
      type: 'percent'



```

**Error: KNX bus did not respond in time (2 secs) to GroupValueRead request for: 7/0/3
Error: KNX bus did not respond in time (2 secs) to GroupValueRead request for: 7/0/4
Error: KNX bus did not respond in time (2 secs) to GroupValueRead request for: 7/0/5
Error: KNX bus did not respond in time (2 secs) to GroupValueRead request for: 8/2/0
Error: KNX bus did not respond in time (2 secs) to GroupValueRead request for: 8/2/1

Could not sync group address '7/0/3' (Energia [Corrente] - Value)
Could not sync group address '7/0/4' (Energia [Fattore Di Potenza] - Value)
Could not sync group address '7/0/5' (Energia [Frequenza] - Value)
Could not sync group address '8/2/0' (Stato Tendone 1 [Balcone] - Value)
Could not sync group address '8/2/1' (Stato Tendone 2 [Balcone] - Value)**

![Schermata 2020-10-22 alle 22 16 20](https://user-images.githubusercontent.com/169086/96925640-c19ea300-14b4-11eb-8cea-20f32712d081.png)

![Schermata 2020-10-22 alle 22 20 21](https://user-images.githubusercontent.com/169086/96925667-cebb9200-14b4-11eb-920e-8bb698a9f9ab.png)
![Schermata 2020-10-22 alle 22 20 26](https://user-images.githubusercontent.com/169086/96925671-cfecbf00-14b4-11eb-8ace-4643aa713084.png)

**Comment by farmio** [comment]
Thanks!

We are aware of this problem. It should be solved with current xknx version. You can track the adoption of the latest xknx version to HA here: https://github.com/home-assistant/core/pull/42026
