### ISSUE TITLE
Cimate: Select byte value operation mode?

### ISSUE THREAD

**Issue by Csstenersen** [XKNX/xknx#484]
I Have a thermostat from Schneier KNX Multitouch Pro
https://download.schneider-electric.com/files?p_enDocType=System+user+guide&p_File_Name=MTN621x-0310_5910_SW_EN.pdf&p_Doc_Ref=MTN621x-0310_5910_SW_EN

the operation modes in thermostat are:
![image](https://user-images.githubusercontent.com/48843914/97233869-02155e00-17e0-11eb-909d-81514b2a6845.png)

This is not corresponding to the DPT20.102.
How can I tweak the climate control to send my wanted 8-bit value for my desired operation modes?

example: Frost/heat protection=Value 4 to the corresponding group adress in the KNX bus.

**Comment by farmio** [comment]
You'd need to add it to several places:
https://github.com/XKNX/xknx/blob/4a6535c8b3af396ed09c33b4f6696e0dabcd6e54/xknx/remote_value/remote_value_climate_mode.py#L26
https://github.com/XKNX/xknx/blob/master/xknx/dpt/dpt_hvac_mode.py
https://github.com/XKNX/xknx/blob/master/xknx/devices/climate_mode.py

I'd rather use a dummy GA and convert the standard operation modes to your proprietary with some kind of simple logic. 
You can then use the DPT 20.102 values in other devices too.
