### ISSUE TITLE
Add more information to Sensor and BinarySensor

### ISSUE THREAD

**Issue by farmio** [XKNX/xknx#498]
It would be nice to have some more information in a Sensor or BinarySensor device. I could imagine good use of 
- source: the source IA of the latest received telegram
- updated_at: a timestamp when the last telegram for the Device was received

To accomplish this I'd propose to store the latest processed `Telegram()` in a RemoteValue instead of the `RemoteValue.payload` attribute. The payload can still be stored as decoded value or just as property returning `RemoteValue.telegram.from_knx()` (or last_telegram or whatever...).
 I'd also like to add a timestamp to the Telegram object to track its reception time.

We would also need to add `src_address` to Telegram() and fill it from cemi_frame.py and RemoteValue._send() to use it later eg. in a `HA.Entity.state_attributes` property.

-----
What do you think?

**Comment by marvin-w** [comment]
Sounds good to me!
