### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by farmio** [XKNX/xknx#629]
Add FAQs to the documentation to handle common questions and issues. 

- How to debug `[xknx.log] Error: KNX bus did not respond in time (2.0 secs) to GroupValueRead request for / [xknx.log] Could not sync group address `
- multiple installations
- cover: inverted % in HA
- received DisconnectRequest
- import from ETS project
- how to set debug level

**Comment by Tolriq** [comment]
Hey there, do you have any timeline about the debug stuff and the could not sync?

I'm having issues with sometimes a random cover not acting when doing operation on a cover group and would like to see if there's something obvious and I should reduce even more the rate_limit.

**Comment by farmio** [comment]
No there is no timeline for any work on this project. 
For debugging tips you can currently see the sticky posts in the discord servers general channel or in the HA community forum. 

PS You should probably not reduce rate_limit, but this is for another issue.
