### ISSUE TITLE
HA: Binary Expose: Unneeded telegrams when attribute changes

### ISSUE THREAD

**Issue by mptei** [XKNX/xknx#643]
**Description of problem:**
Create a binary expose for a light entity.  Switch the light on sends an "on" telegram. OK!
Any change of the brightness sends an "on" telegram too. => unneeded

- [ ] using xknx standalone
- [x] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 0.17.1 / 2021.3.4
- last working xknx / Home-Assistant release (if known): -

**KNX installation:**

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**
- type: binary
  entity_id: light.labor
  address: "1/1/8"

**Traceback (if applicable):**

In expose.py the problem seems to be that only attribute changes are checked. When there is no attribute given, any change event leads to a knx telegram with the current state of the entity.

**Comment by farmio** [comment]
Legit. As you seem to have already located the problem, do you want to do a PR to change this?

**Comment by mptei** [comment]
Yes, I'll create a PR.Am 23.03.2021 18:58 schrieb Matthias Alphart ***@***.***>:
Legit. As you seem to have already located the problem, do you want to do a PR to change this?

**Comment by farmio** [comment]
Great. Please target it against HA.core as the custom component here is currently not up to date.
