### ISSUE TITLE
Support for maximum Setpoint Shift

### ISSUE THREAD

**Issue by TinusK** [XKNX/xknx#75]
Usually, by using Setpoint Shift, a maximum of this shift is defined in the Actuator using ETS. This maximum is normally not returned on the KNX bus and therefor XKNX does not know it. If a shift is set higher then the max shift, then the Actuator returns a new target temperature corresponding to the max shift. Some Actuators, like mine, does also not send the current shift.

For example:
Current Setpoint: 21C
Setpoint size: 0.5K
Max Setpoint shift: 3.0K

If new temp is set to 25C, the KNX bus (Actuator) returns 24C. However internally (in XKNX) the shift is still 4K (if not returned on the bus by the Actuator - like mine) and subsequently, the next shift is miscalculated.

Therefor it would be nice to incorporate a maximum setpoint shift. Like:
setpoint_max_shift: 3.0

**Comment by Julius2342** [comment]
I implemented this. Please check current custom_components of master or https://github.com/home-assistant/home-assistant/pull/10388
