### ISSUE TITLE
HA 2021.11.0b0 reload KNX config resets number entities

### ISSUE THREAD

**Issue by DirkMu** [XKNX/xknx#786]
When executing service KNX: Reload KNX configuration the values of all (knx) number entities are reset to 0. 

- [ ] using xknx standalone
- [X] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 2021.11.0b0
- last working xknx / Home-Assistant release (if known): HA 2021.10.6 (I guess)

**Traceback (if applicable):**
I just execute the service.

**Comment by farmio** [comment]
Woha, theres a lot of warnings 😬
Nevertheless, this is what we were looking for:
```log
"### Last state for number.ws_dach_wind_ext_gw1: <state number.ws_dach_wind_ext_gw1=unavailable; min=0.0, max=10.0, step=0.01, mode=box, unit_of_measurement=m/s, friendly_name=WS Dach: Windalarm 1 Schwellwert @ 2021-10-29T19:33:04.118866+02:00>
```
The state seems to be changed to "unavailable" just before removing the entity. Thus it can't be restored. Let's see why...

**Comment by DirkMu** [comment]
Yes 😊 The template int and float check they introduced in 2021.9. Every time I reload the KNX config I get warnings from GAs not responding (which is correct) and the templates. I reloaded the config 4 times. Thus the warning were quadrupled. 😉 You will find the print result four times in the log, too.

**Comment by farmio** [comment]
You can disable reading non-responding GAs speeding up KNX entity setup 😉

**Comment by DirkMu** [comment]
Are you talking about the sync_state? I need to read it from the bus actively. What happen during starup when using the default value "expire"? Will it attempt to read it from the bus during startup, too?

**Comment by farmio** [comment]
Yep, on startup and then after 1 hour - incoming or outgoing telegrams reset the timer.
So the GAs generating these warnings are readable? eg. 7/0/44 (lots of 7/0/{30-59})

**Comment by farmio** [comment]
@DirkMu Thanks for beta testing and helping find the cause of this issue! 👍
If you have more questions about the StateUpdater or passive addresses feel free to join us on [discord](https://discord.gg/EuAQDXU)!

**Comment by DirkMu** [comment]
I just tested it in b2. It seems to be fixed. Thanks. 

With regards to the GAs. Yes they're basically readable. At least according to ETS. I assume the devices are rather slow (old KNX RF smoke detectors.) I set sync_state to init. Maybe false is the better approach here since HA receives an update later.

**Comment by farmio** [comment]
Ah if they are really slow (like >2 seconds slow) I guess best to just live with the warnings. If they were non-RF it would be odd - I don't have any experience with RF so 🤷‍♂️

**Comment by marvin-w** [comment]
For reference, when https://github.com/home-assistant/core/pull/58656 is merged the reload service will no longer exist. KNX can be reloaded from the Integrations page then.
