### ISSUE TITLE
Improve requirements.

### ISSUE THREAD

**Issue by encbladexp** [XKNX/xknx#79]
Currently we use this requirements:
```
pyyaml>=3.11,<4
pylint
netifaces
tox
coveralls
pytest
pytest-cov
pytest-timeout
```

We should improve this a little bit:
* Split requirements.txt in `requirements/base.txt` and `requirements/development.txt`
* Always pin requirements to releases, currently it is easly possible to break things if requirements get updates upstream, also updates on client system get not applied, as the requirement `foobar` is met after installation, only `foobar==X.y.z` would force an update on `pip install -r requirements/base.txt`

I can provide an pull request if required, also i would recommend integration of requires.io, so we have an status on our pinned requirements.

**Comment by Julius2342** [comment]
all that makes totally sense ...

**Comment by encbladexp** [comment]
I create a Pull Request.

**Comment by Julius2342** [comment]
That would be great!
