### ISSUE TITLE
xknx setup or install failed 

### ISSUE THREAD

**Issue by Saloom12** [XKNX/xknx#792]
Hello , i have my knx project and it has a line coupler for 3 floors and i can’t communicate with my knx through home assistant unless i changed the configuration to

`xknx`
  `tunneling:`
    `host:` xxx.xxx.xxx
![xknx](https://user-images.githubusercontent.com/12776848/139871094-5fc033db-4c73-4425-bade-9d18efc7362d.png)

> ### (but i have this problem it says error xknx setup failed why?)

**Comment by marvin-w** [comment]
If you are using KNX in the Home Assistant app without any changes you should use `knx` as the root yaml key. `xknx` is only used for our custom component (same logic - just in this repository).

Please check the KNX documentation https://www.home-assistant.io/integrations/knx/.
