### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by yugeshk** [XKNX/xknx#804]
Hi,

sorry for bothering you guys, but I'm confused as to how you've setup your github pages. For example, you do an `{% include head.html %}` in `docs/_layouts/default.html` but you don't have any `_includes` folder at all?
Am I missing something?

Thanks!

**Comment by marvin-w** [comment]
Hi,

It's part of the `just-the-docs` Gem.

https://github.com/pmarsceill/just-the-docs
i.e: https://github.com/pmarsceill/just-the-docs/blob/master/_includes/head.html

**Comment by yugeshk** [comment]
So I simply copied your docs source to make a website but github pages doesn't allow me to deploy it.
Only content is changed. You can see the repo here - https://github.com/yugeshk/systems-website
![image](https://user-images.githubusercontent.com/31157397/142473501-03e6782f-9be6-4caf-b9d6-e11ff7f60576.png)

**Comment by marvin-w** [comment]
> So I simply copied your docs source to make a website but github pages doesn't allow me to deploy it.
Only content is changed. You can see the repo here - https://github.com/yugeshk/systems-website

Then now is the right time to actually learn something about what you've copied :).

We don't use github pages, but netlify for deployments, so can't really help there. Also, this is an issue tracker and not a support forum. Please join our discord if you need help.
