### ISSUE TITLE
Add support for DPT 14.019 Electrical Current (A) & DPT 14.027 Electrical Potential (V)

### ISSUE THREAD

**Issue by ssoerensen** [XKNX/xknx#84]
It would be awesome to be able to read those two dpt's

**Comment by Roemer** [comment]
It seems that this is a 4-Octet Float Value. Implementing this would add pretty much all 14.xxx DPTs. Find attached the specification for it:
![image](https://user-images.githubusercontent.com/393641/34581350-63cb80da-f190-11e7-8c25-a3a1a1b429f2.png)

**Comment by JohanElmis** [comment]
We are working on this, and it will be available in the library soon.

**Comment by JohanElmis** [comment]
For a preview, look at: https://github.com/Straeng/xknx Fork: add_electric_sensors

**Comment by Julius2342** [comment]
I think this is done. Please reopen if something is missing.
