### ISSUE TITLE
Would it be possible to implement my own device with this library

### ISSUE THREAD

**Issue by firesurfer** [XKNX/xknx#883]
Hi everyone,
I would like to use python on an raspberry pi to communicate with various KNX devices via a KNX gateway and to provide some information for some KNX devices.
As far as I can see reading sensor / commanding actuators is possible with this library.

But would it be possible to implement my own sensor on the raspberry pi with this library?

Thanks a lot in advance.

**Comment by farmio** [comment]
Hi 👋!
Yes, that's what it's there for - sending and receiving various Telegrams.
