### ISSUE TITLE
Feature request: Support `device_class` for switches in HA integration

### ISSUE THREAD

**Issue by envy** [XKNX/xknx#948]
Switches can have a device class (see https://www.home-assistant.io/integrations/switch/) but I cannot set it from the knx integration.

It would be nice to be able to set it, like we can set it for sensors.

**Comment by marvin-w** [comment]
Hey! The only reason we set it for sensors is that we need to know the DPT Type that is used to decode the payload from the bus.

We do not intend to add this to switches. Please use the [customization feature](https://www.home-assistant.io/docs/configuration/customizing-devices/#device_class) in Home Assistant which is perfectly able to handle your use case without us even intervening :).
