### ISSUE TITLE
Feature request: Add control data type of VRV air conditioner

### ISSUE THREAD

**Issue by shenliushuai** [XKNX/xknx#975]
Want to add the control data type of VRV air conditioner and support HomeAssistant

For example, the modes of VRV air conditioners include cooling, heating, air supply, dehumidification, automatic, etc.
The data type is: DTP6.0.10
Is it possible to send schema data type when
When DTP6.0.10=1, it is cooling
When DTP6.0.10=2, it is heating
When DTP6.0.10=3, it is supply air
When DTP6.0.10=4, it is dehumidification
Automatic when DTP6.0.10=5

Of course, what is the specific DTP6.0.10 value and what is the corresponding mode, which can be defined according to your own needs

The same wind speed is the same, and the data type used for the wind speed is also DTP6.0.10
Low speed when DTP6.0.10=1
Medium speed when DTP6.0.10=2
High speed when DTP6.0.10=3
Automatic when DTP6.0.10=4

Of course, what is the specific DTP6.0.10 value and what is the corresponding mode, which can be defined according to your own needs

This is more suitable for users who use VRV air conditioners at home. They can write it directly in the configuration file of HomeAssistant, and there is no need to do transfer on Node-Red.

**Comment by farmio** [comment]
What exact device is this (the KNX gateway device)?

I think DPT 6.010 is wrong - this is a datapoint containing signed integers, not any modes. It may work fine, as the payload is apparently the same, but it doesn't really help with implementing this. 
Same for the speed DPT - it doesn't make sense to be able to send `-5` as speed.

If it is some proprietary DPT we probably won't integrate this - but there are some specified DPTs (like 20.105) that may fit here.

**Comment by farmio** [comment]
To me this looks like the perfect example of a proprietary DPT - the values of each mode are not specified in KNX specifications, but even user configurable. See https://www.knx.org/wAssets/docs/downloads/Certification/Interworking-Datapoint-types/03_07_02-Datapoint-Types-v02.02.01-AS.pdf

As this seems to be the controlling end of the chain, what is the receiving device?

**Comment by shenliushuai** [comment]
Well, that should be a special data type given by us for VRV air conditioners or air conditioners controlled by Modbus protocol, but is it possible to consider adding it to xknx, so that KNX systems all over the world can be used.

The receiving device is the KNX system air conditioning protocol gateway. The value specified by the data type of this DTP6.010 can also be changed, but the mode and wind speed are generally the ones I sent above.

In the KNX system, we can connect VRV air conditioners or other control protocol type air conditioners through the air conditioner protocol gateway, such as: Daikin, Hitachi, Toshiba, etc.

There are also air conditioners such as Modbus protocol, which are also connected to the KNX system through an air conditioner protocol gateway.

**Comment by farmio** [comment]
> The receiving device is the KNX system air conditioning protocol gateway. 

I'm gonna try once more: what is this device? What manufacturer / type? Is it an Intesis thing?

> The value specified by the data type of this DTP6.010 can also be changed

Then just use DPT 20.105 - its specified and already supported by xknx.

**Comment by shenliushuai** [comment]
VRV Air Conditioning Protocol Gateway

![image](https://user-images.githubusercontent.com/61911709/175312811-46df5825-d1da-4e06-b213-25a627c54542.png)
